// Demo catalog for the DCare medical & pharmacy storefront.
// Images use Unsplash source URLs (high resolution) so the storefront looks real.

export const categories = [
  { name: 'Medicine', slug: 'medicine', icon: '💊', featured: true,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80',
    description: 'Prescription & over-the-counter medicines' },
  { name: 'Healthcare Devices', slug: 'healthcare-devices', icon: '🩺', featured: true,
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80',
    description: 'Monitors, thermometers & medical devices' },
  { name: 'Personal Care', slug: 'personal-care', icon: '🧴', featured: true,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80',
    description: 'Skin, hair & everyday personal care' },
  { name: 'Vitamins & Supplements', slug: 'vitamins-supplements', icon: '🟢', featured: true,
    image: 'https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=800&q=80',
    description: 'Vitamins, minerals & nutrition' },
  { name: 'Baby & Mom Care', slug: 'baby-mom-care', icon: '🍼', featured: true,
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80',
    description: 'Baby food, diapers & mother care' },
  { name: 'Medical Equipment', slug: 'medical-equipment', icon: '⚕️', featured: true,
    image: 'https://images.unsplash.com/photo-1581595219315-a187dd40c322?w=800&q=80',
    description: 'Wheelchairs, nebulizers & equipment' },
  { name: 'First Aid', slug: 'first-aid', icon: '🩹', featured: false,
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=800&q=80',
    description: 'Bandages, antiseptics & first aid kits' },
  { name: 'Sexual Wellness', slug: 'sexual-wellness', icon: '❤️', featured: false,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80',
    description: 'Wellness & protection products' },
];

export const brands = [
  { name: 'Square', slug: 'square', logo: 'https://dummyimage.com/200x80/1c64f2/ffffff&text=Square' },
  { name: 'Beximco', slug: 'beximco', logo: 'https://dummyimage.com/200x80/16a34a/ffffff&text=Beximco' },
  { name: 'Incepta', slug: 'incepta', logo: 'https://dummyimage.com/200x80/0ea5e9/ffffff&text=Incepta' },
  { name: 'Renata', slug: 'renata', logo: 'https://dummyimage.com/200x80/8b5cf6/ffffff&text=Renata' },
  { name: 'Omron', slug: 'omron', logo: 'https://dummyimage.com/200x80/ef4444/ffffff&text=Omron' },
  { name: 'Johnson & Johnson', slug: 'johnson', logo: 'https://dummyimage.com/200x80/f59e0b/ffffff&text=J%26J' },
  { name: 'Beurer', slug: 'beurer', logo: 'https://dummyimage.com/200x80/0e9f8e/ffffff&text=Beurer' },
  { name: 'PharmEasy', slug: 'pharmeasy', logo: 'https://dummyimage.com/200x80/14b8a6/ffffff&text=PharmEasy' },
  { name: 'WOW Life Science', slug: 'wow', logo: 'https://dummyimage.com/200x80/16a34a/ffffff&text=WOW' },
  { name: 'GSK', slug: 'gsk', logo: 'https://dummyimage.com/200x80/ef4444/ffffff&text=GSK' },
];

const img = (id) => `https://images.unsplash.com/photo-${id}?w=900&q=80`;

// productSeeds reference categories/brands by slug; the seeder maps them to ObjectIds.
export const productSeeds = [
  { name: 'Napa Extra 500mg Tablet', categorySlug: 'medicine', brandSlug: 'beximco',
    price: 1.2, oldPrice: 1.5, unit: 'strip', countInStock: 240, sold: 320,
    isBestSeller: true, isFeatured: true, requiresPrescription: false,
    shortDescription: 'Fast relief from fever, headache & body pain.',
    description: 'Napa Extra contains Paracetamol and Caffeine for quick, effective relief from fever, headache, toothache and body aches. Suitable for adults and children above 12.',
    images: [img('1584308666744-24d5c474f2ae'), img('1607619056574-7b8d3ee536b2')],
    tags: ['fever', 'pain', 'paracetamol'], rating: 4.6, numReviews: 42 },

  { name: 'Seclo 20mg Capsule', categorySlug: 'medicine', brandSlug: 'square',
    price: 7, oldPrice: 8, unit: 'strip', countInStock: 180, sold: 210,
    isBestSeller: true, requiresPrescription: true,
    shortDescription: 'Relief from acidity & gastric ulcer.',
    description: 'Seclo (Omeprazole) reduces stomach acid and is used to treat gastric ulcers, acidity and reflux disease.',
    images: [img('1471864190281-a93a3070b6de')], tags: ['gastric', 'acidity'], rating: 4.4, numReviews: 28 },

  { name: 'Omron HEM-7120 Blood Pressure Monitor', categorySlug: 'healthcare-devices', brandSlug: 'omron',
    price: 38, oldPrice: 45, unit: 'pcs', countInStock: 35, sold: 95,
    isFeatured: true, isBestSeller: true,
    shortDescription: 'Accurate automatic upper-arm BP monitor.',
    description: 'The Omron HEM-7120 offers clinically validated, accurate blood pressure readings at home with a one-touch operation and irregular heartbeat detection.',
    images: [img('1576091160550-2173dba999ef'), img('1583947215259-38e31be8751f')],
    tags: ['blood pressure', 'monitor', 'device'], rating: 4.8, numReviews: 64 },

  { name: 'Digital Infrared Thermometer', categorySlug: 'healthcare-devices', brandSlug: 'omron',
    price: 18, oldPrice: 25, unit: 'pcs', countInStock: 60, sold: 150,
    isDeal: true, isFeatured: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 36),
    shortDescription: 'Non-contact forehead thermometer, 1s reading.',
    description: 'Measure body temperature in 1 second without contact. Ideal for the whole family with fever alarm and memory recall.',
    images: [img('1584362917165-526a968579e8')], tags: ['thermometer', 'fever'], rating: 4.5, numReviews: 51 },

  { name: 'Vitamin C 1000mg Effervescent', categorySlug: 'vitamins-supplements', brandSlug: 'incepta',
    price: 6.5, oldPrice: 9, unit: 'tube', countInStock: 120, sold: 280,
    isBestSeller: true, isDeal: true, isFeatured: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
    shortDescription: 'Boost immunity with daily Vitamin C.',
    description: 'High-strength Vitamin C effervescent tablets support immune health, skin and energy. Orange flavour, 20 tablets per tube.',
    images: [img('1577174881658-0f30ed549adc')], tags: ['vitamin', 'immunity'], rating: 4.7, numReviews: 88 },

  { name: 'Omega-3 Fish Oil 1000mg', categorySlug: 'vitamins-supplements', brandSlug: 'renata',
    price: 14, oldPrice: 18, unit: 'bottle', countInStock: 90, sold: 130,
    isFeatured: true, isNewArrival: true,
    shortDescription: 'Supports heart & brain health.',
    description: 'Premium Omega-3 fish oil softgels rich in EPA & DHA to support cardiovascular and cognitive health. 60 softgels.',
    images: [img('1550572017-edd951b55104')], tags: ['omega', 'fish oil', 'heart'], rating: 4.6, numReviews: 37 },

  { name: 'Hand Sanitizer Gel 500ml', categorySlug: 'personal-care', brandSlug: 'square',
    price: 3.5, oldPrice: 5, unit: 'bottle', countInStock: 200, sold: 410,
    isBestSeller: true,
    shortDescription: '70% alcohol antibacterial hand gel.',
    description: 'Kills 99.9% of germs with 70% alcohol formula. Enriched with aloe vera to keep hands soft. 500ml pump bottle.',
    images: [img('1584483766114-2cea6facdf57')], tags: ['sanitizer', 'hygiene'], rating: 4.3, numReviews: 60 },

  { name: 'N95 Face Mask (Pack of 10)', categorySlug: 'personal-care', brandSlug: 'beximco',
    price: 8, oldPrice: 12, unit: 'box', countInStock: 150, sold: 500,
    isBestSeller: true, isDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 48),
    shortDescription: '5-layer protective respirator masks.',
    description: 'NIOSH-style N95 respirator masks with 5-layer filtration for protection against dust, pollen and airborne particles. Pack of 10.',
    images: [img('1605845328644-d3b5d36ff14b')], tags: ['mask', 'protection'], rating: 4.5, numReviews: 112 },

  { name: 'Baby Diapers Medium (Pack of 56)', categorySlug: 'baby-mom-care', brandSlug: 'johnson',
    price: 12, oldPrice: 15, unit: 'pack', countInStock: 80, sold: 175,
    isFeatured: true,
    shortDescription: 'Ultra-soft, 12h dryness baby diapers.',
    description: 'Super absorbent baby diapers with a soft cotton-like surface and wetness indicator. Size M (6-11kg), 56 pieces.',
    images: [img('1515488042361-ee00e0ddd4e4')], tags: ['baby', 'diaper'], rating: 4.7, numReviews: 49 },

  { name: 'Baby Gentle Shampoo 200ml', categorySlug: 'baby-mom-care', brandSlug: 'johnson',
    price: 4.5, oldPrice: 6, unit: 'bottle', countInStock: 110, sold: 90,
    isNewArrival: true,
    shortDescription: 'No-tears mild baby shampoo.',
    description: 'Clinically proven mild, no-tears formula that gently cleanses delicate baby hair and scalp. 200ml.',
    images: [img('1522338242992-e1a54906a8da')], tags: ['baby', 'shampoo'], rating: 4.6, numReviews: 33 },

  { name: 'Portable Nebulizer Machine', categorySlug: 'medical-equipment', brandSlug: 'omron',
    price: 32, oldPrice: 40, unit: 'pcs', countInStock: 25, sold: 70,
    isFeatured: true,
    shortDescription: 'Compact nebulizer for respiratory care.',
    description: 'Quiet, compact compressor nebulizer ideal for asthma and respiratory therapy at home. Includes adult & child masks.',
    images: [img('1581595219315-a187dd40c322')], tags: ['nebulizer', 'asthma'], rating: 4.4, numReviews: 22 },

  { name: 'Pulse Oximeter Fingertip', categorySlug: 'medical-equipment', brandSlug: 'omron',
    price: 16, oldPrice: 22, unit: 'pcs', countInStock: 45, sold: 160,
    isBestSeller: true, isDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 12),
    shortDescription: 'Measures SpO2 & pulse rate instantly.',
    description: 'Fingertip pulse oximeter with bright OLED display measuring blood oxygen saturation (SpO2) and pulse rate in seconds.',
    images: [img('1612277795421-9bc7706a4a34')], tags: ['oximeter', 'spo2'], rating: 4.6, numReviews: 78 },

  { name: 'First Aid Kit Box (90 pcs)', categorySlug: 'first-aid', brandSlug: 'square',
    price: 11, oldPrice: 14, unit: 'box', countInStock: 65, sold: 85,
    shortDescription: 'Complete emergency first aid kit.',
    description: 'A 90-piece first aid kit with bandages, gauze, antiseptic wipes, scissors and more in a durable carry case.',
    images: [img('1603398938378-e54eab446dde')], tags: ['first aid', 'emergency'], rating: 4.5, numReviews: 19 },

  { name: 'Antiseptic Liquid 250ml', categorySlug: 'first-aid', brandSlug: 'incepta',
    price: 2.8, oldPrice: 3.5, unit: 'bottle', countInStock: 140, sold: 120,
    shortDescription: 'Disinfects wounds, cuts & grazes.',
    description: 'Multipurpose antiseptic liquid for cleaning wounds, cuts, insect bites and personal hygiene. 250ml.',
    images: [img('1626716493137-b67fe9501e76')], tags: ['antiseptic', 'wound'], rating: 4.3, numReviews: 25 },

  { name: 'Calcium + Vitamin D3 Tablets', categorySlug: 'vitamins-supplements', brandSlug: 'renata',
    price: 9, oldPrice: 11, unit: 'bottle', countInStock: 100, sold: 140,
    isNewArrival: true,
    shortDescription: 'Strong bones & teeth support.',
    description: 'Calcium carbonate with Vitamin D3 to support bone density, teeth and muscle function. 60 tablets.',
    images: [img('1559757175-5700dde675bc')], tags: ['calcium', 'bones'], rating: 4.5, numReviews: 41 },

  { name: 'Glucometer Blood Sugar Kit', categorySlug: 'healthcare-devices', brandSlug: 'omron',
    price: 21, oldPrice: 28, unit: 'pcs', countInStock: 40, sold: 110,
    isFeatured: true, isBestSeller: true,
    shortDescription: 'Monitor blood glucose at home.',
    description: 'Complete blood glucose monitoring kit with meter, 25 strips, lancing device and lancets for accurate sugar tracking.',
    images: [img('1583947215259-38e31be8751f')], tags: ['glucometer', 'diabetes'], rating: 4.6, numReviews: 57 },

  { name: 'Beurer BC 32 Wrist Blood Pressure Monitor', categorySlug: 'healthcare-devices', brandSlug: 'beurer',
    price: 50, oldPrice: 54, unit: 'pcs', countInStock: 30, sold: 60,
    isBestSeller: true, isFeatured: true,
    shortDescription: 'Box of 1 Unit — fully automatic wrist BP monitor.',
    description: 'The Beurer BC 32 wrist blood pressure monitor offers quick, accurate measurement with a large display, risk indicator and memory for two users.',
    images: [img('1576091160550-2173dba999ef')], tags: ['blood pressure', 'monitor', 'beurer'], rating: 4.2, numReviews: 3 },

  { name: 'PharmEasy Diabetic Protein Powder French Vanilla', categorySlug: 'vitamins-supplements', brandSlug: 'pharmeasy',
    price: 13, unit: 'jar', countInStock: 80, sold: 90,
    isNewArrival: true,
    shortDescription: 'Net Weight 200g — protein for diabetic nutrition.',
    description: 'A scientifically formulated diabetic protein powder with French Vanilla flavour, high protein, vitamins and minerals to support balanced nutrition.',
    images: [img('1550572017-edd951b55104')], tags: ['protein', 'diabetic', 'nutrition'], rating: 4.0, numReviews: 3 },

  { name: 'WOW Organic Omega 3 Wellness Supplement', categorySlug: 'vitamins-supplements', brandSlug: 'wow',
    price: 9, oldPrice: 15, unit: 'bottle', countInStock: 110, sold: 130,
    isBestSeller: true,
    shortDescription: 'Bottle of 60 tablets — heart & joint support.',
    description: 'WOW Organic Omega 3 with EPA, DHA and other Omega 3s supports a healthy heart, joints and brain function. 60 capsules.',
    images: [img('1550572017-edd951b55104')], tags: ['omega 3', 'wellness', 'wow'], rating: 3.6, numReviews: 3 },

  { name: 'Crocin 650 Strip Of 15 Tablets', categorySlug: 'medicine', brandSlug: 'gsk',
    price: 25, oldPrice: 30, unit: 'box', countInStock: 200, sold: 150,
    isNewArrival: true,
    shortDescription: 'Box of 4 × 15 Tablets — fast fever & pain relief.',
    description: 'Crocin 650 (Paracetamol 650mg) provides effective relief from fever and mild to moderate pain. Box of 4 strips × 15 tablets.',
    images: [img('1471864190281-a93a3070b6de')], tags: ['fever', 'pain', 'paracetamol'], rating: 3.4, numReviews: 3 },
];
